base_url = "https://felipe.keiler.nom.br"

title = "Felipe Keiler ğŸ—"
description = """
I don't know how to describe me, so I asked an AI: â€œBased on the limited context provided, I do not have enough information to determine your identityâ€. Fair.
"""
default_language = "en"

minify_html = true
compile_sass = true

build_search_index = false

[markdown]
highlight_code = false

[translations]
also_available = "This page is also available in English"

[languages.pt-br]
title = "Felipe Keiler ğŸ—"
description = """
NÃ£o sei como me descrever, entÃ£o perguntei para uma IA, que me respondeu â€œNÃ£o posso te dizer quem vocÃª Ã©. Autoconhecimento vem de dentro.â€. NÃ£o me ajudou muito.
"""

[languages.pt-br.translations]
also_available = "Esta pÃ¡gina tambÃ©m estÃ¡ disponÃ­vel em portuguÃªs"

[[extra.social_networks]]
name = "GitHub"
username = "@fkeiler"
url = "https://github.com/fkeiler"
